BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS "anime" (
	"id"	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	"anilistid"	TEXT NOT NULL UNIQUE,
	"timer"	INTEGER NOT NULL,
	"title"	TEXT,
	"cover"	TEXT,
	"color"	TEXT
);
CREATE TABLE IF NOT EXISTS "users_anime" (
	"user_id"	INTEGER NOT NULL,
	"anime_id"	INTEGER NOT NULL,
	FOREIGN KEY("user_id") REFERENCES "users"("id") ON UPDATE CASCADE ON DELETE CASCADE,
	FOREIGN KEY("anime_id") REFERENCES "anime"("id") ON UPDATE CASCADE ON DELETE CASCADE,
	PRIMARY KEY("user_id","anime_id")
);
CREATE TABLE IF NOT EXISTS "users" (
	"id"	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	"discordid"	TEXT NOT NULL UNIQUE,
	"username" TEXT
);
COMMIT;
